---
micronaut:
  application:
    name: bookamanagement

---
jackson:
  # 空文字がnull扱いになるのを防ぐために設定
  # Nullのときは、項目を省略
  # http://fasterxml.github.io/jackson-annotations/javadoc/2.9/com/fasterxml/jackson/annotation/JsonInclude.Include.html
  serializationInclusion: NON_NULL
jooq:
  datasources:
    default:
      sql-dialect: 'MYSQL'

---
# TODO dev,stg,prdなど環境によって読み込む設定ファイルを切り替える https://docs.micronaut.io/latest/guide/config.html
datasources:
  default:
    url: jdbc:mysql://localhost:33060/bookmanagement
    username: root
    password: ""
    driverClassName: com.mysql.cj.jdbc.Driver

---
micronaut:
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

--- openapi
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**